require("trouble").setup()

-- Lua
vim.keymap.set("n", "<leader>xx", function()
  vim.cmd("Trouble diagnostics toggle")
end)
vim.keymap.set("n", "<leader>xd", function()
  vim.cmd("Trouble diagnostics toggle filter.buf=0")
end)
vim.keymap.set("n", "<leader>xq", function()
  vim.cmd("Trouble qflist toggle")
end)
vim.keymap.set("n", "<leader>xl", function()
  vim.cmd("Trouble loclist toggle")
end)
vim.keymap.set("n", "gR", function()
  vim.cmd("Trouble lsp toggle focus=false win.position=right")
end)
