listen_on unix:/tmp/kitty
allow_remote_control yes

font_family Berkeley Mono Variable
bold_font Berkeley Mono Variable Bold
italic_font Berkeley Mono Variable Italic
bold_italic_font Berkeley Mono Variable Bold Italic
font_size 12.0

cursor_shape block
cursor_blink_interval 1
cursor_stop_blinking_after 0
cursor_shape_unfocused hollow

shell_integration no-cursor

url_color #0087bd
url_style curly
open_url_with default
detect_urls yes
show_hyperlink_targets yes
underline_hyperlinks hover
copy_on_select no
focus_follows_mouse yes

include ./theme.conf

macos_quit_when_last_window_closed yes
macos_titlebar_color background
