blinking-cursor = true
performance = "High"
disable-unfocused-render = false
use-fork = false
line-height = 1.0
theme = "tokyonight"
padding-x = 10.0
cursor = "▇"
env-vars = []
option-as-alt = "false"
ignore-selection-fg-color = false

[navigation]
mode = "BottomTab"
use-current-path = false

[window]
width = 600
height = 400
mode = "Windowed"

[background]

[shell]
program = ""
args = ["--login"]

[fonts]
size = 12.0
extras = []

[fonts.regular]
family = "Berkeley Mono"
weight = 400
style = "normal"

[fonts.bold]
family = "Berkeley Mono"
weight = 800
style = "normal"

[fonts.bold-italic]
family = "Berkeley Mono"
weight = 800
style = "italic"

[fonts.italic]
family = "Berkeley Mono"
weight = 400
style = "italic"

[developer]
enable-fps-counter = false
log-level = "OFF"

[bindings]
keys = []

